# site name
prefixName: 酷喵森の凉叶
siteName: 
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /hexobolg/imgkumaio.jpeg
url: https://mma324.github.io
description: Live your life with passion! With some drive!
cdn: https://cdn.jsdelivr.net/gh/mma324/hexobolg
pjax: 1
# 1开启
mathjax: 0

notice: 欢迎来到我的博客！
lazyloadImg: https://cdn.jsdelivr.net/gh/mma324/hexobolg/hexobolg/img1441607770749111.gif

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    标签: {path: /tags/, fa: fa-tag  faa-shake }, 
    美化: {path: /categories/转载/, fa: fa-archive faa-shake }
  } }
  分类: {path: /categories/, fa: fa-bookmark faa-shake }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    读书: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/,fa: fa-paper-plane faa-float faa-fast }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
    RSS: { path: /atom.xml, fa: fa-rss faa-pulse },
  } }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 6
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/mma324/hexobolg@master/hexobolg/imgdongmia (4).webp
  - https://cdn.jsdelivr.net/gh/mma324/hexobolg@master/hexobolg/imgdongmia (1).webp
  - https://cdn.jsdelivr.net/gh/mma324/hexobolg@master/hexobolg/imgdongmia (2).webp
  - https://cdn.jsdelivr.net/gh/mma324/hexobolg@master/hexobolg/imgdongmia (3).webp
  - https://cdn.jsdelivr.net/gh/mma324/hexobolg@master/hexobolg/imgdongmia (5).webp
  - https://cdn.jsdelivr.net/gh/mma324/hexobolg@master/hexobolg/imgdongmia (6).webp
  

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dim 

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /hexobolg/imgtu2 (2).webp}
  - {url: http://sce.bilbili.m/2749, title: Bilibili, desc: 博主的b站视频, img: /hexobolg/imgtu1 (4).webp}
  - {url: /, title: kumaio的bolg, desc: 技术服务, img: /hexobolg/imghaoxa.webp }



# your site build time or founded date
siteBuildingTime: 04/09/2020

#social  url, img PC端配置
social:
  github: {url: http://github.com/mma324, img: /hexobolg/imggithub.png}
  #sina: {url: http://weibo.com/mashirozx?is_all=1, img: /hexobolg/imgsina.png }
  wangyiyun: {url: https://music.163.com/#/user/home?id=342164341, img: /hexobolg/imgwangyiyun.png}
  #zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/zhihu.png}
  email: {url:ningliang65@gmail.com , img: /hexobolg/imgemail.svg}
   #wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /hexobolg/imgwechat.png}
  BILIBILI: {url: https://space.bilibili.com/45786813, img: /hexobolg/imgbilibili.png}
  QQ:   {url: http://wpa.qq.com/msgrd?v=3&uin=1900661758&site=qq&menu=yes, img: /hexobolg/imgqq.png}
#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/mma324, fa: fa-github, color: 333}
  #weibo: {url: http://weibo.com/mashozx?s_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: http://wpa.qq.com/msgrd?v=3&uin=1900661758&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal: https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/AliPayQR.jpg
  wechat: /img/custom/donate/WeChanQR.jpg
  wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 2178543853
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ

word_count: true
# 是否开启字数统计
#不需要使用，直接设置值为false，或注释掉
